version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: currency_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


